
version: '3.8' 

services:

  frontend:
    build: ./frontend
    ports:
      - "80:80" 
    volumes:
      - ./frontend:/usr/share/nginx/html
    container_name: pixel-health-frontend

  backend:
    build: ./backend 
    ports:
      - "5000:5000" 
    volumes:

      - ./backend:/app
    container_name: pixel-health-backend 
    depends_on:
      - frontend
